name: Deploy to Firebase Function via GitHub Actions

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT }}" > "$HOME"/firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/firebase_key.json

      - name: Download deps
        working-directory: src
        run: npm install

      - name: Deploy Function
        if: ${{ env.CI == 'true' }}
        run: npx firebase-tools deploy --only functions:uploader --project fantom-csb --token ${{ secrets.FIREBASE_TOKEN }}
